
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2'
version_full = 'b47193ce7e048dea4fe4a5f630f59e8d4907a17c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

